version: '3.1'
services:
  backend:
    build:
      context: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/var/www/backend

  ui:
    build:
      context: ui
    ports:
      - "8888:8888"
    volumes:
      - ./ui:/var/www/ui
